name: Build

on:
  workflow_call:
    inputs:
      push:
        required: true
        type: boolean
    outputs:
      image:
        description: "The docker image tag"
        value: ${{ jobs.build.outputs.image }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.print.outputs.image }}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ inputs.push }}
          tags: hello-test

      - name: List
        run:  docker image ls --all

      - name: Print image
        id: print
        run:  echo "::set-output name=image::hello-test"
