name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint
        run: echo "Linting..."

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint
        run: echo "Testing..."

  build:
    runs-on: ubuntu-latest
    needs: [ lint, test]
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: hello-test

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test, build]
    environment: test-production
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Deploy
        run: echo "deploying..."
