name: Deploy

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Deploy
        run: echo "deploying image ${{ inputs.image }}..."
