name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test-production
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Deploy
        run: echo "deploying..."
